name: Pack Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pack Chrome Extension
        run: |
          mkdir -p dist
          zip -r dist/extension.zip . -x "*.git*" -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: dist/extension.zip
          if-no-files-found: error
          retention-days: 0
          compression-level: 9
          overwrite: true
          include-hidden-files: false
